services:
  hclapi:
    image: ghcr.io/ju4n97/hclapi:latest
    container_name: hclapi-02-api
    volumes:
      - ./Hclapifile:/etc/hclapi/Hclapifile:ro
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped