version: '3'

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: List available tasks
    cmd: task --list

  cli-docs:
    desc: Generate CLI reference
    cmd: go run -tags docs ./cmd/hclapi/docs.go ./cmd/hclapi/cli.go ./cmd/hclapi/serve.go

  cli-man:
    desc: Generate man pages
    cmd: go run -tags man ./cmd/hclapi/man.go ./cmd/hclapi/cli.go ./cmd/hclapi/serve.go

  docs-serve:
    desc: Serve documentation
    dir: docs
    cmd: mdbook serve

  docs-build:
    desc: Build documentation
    dir: docs
    cmd: mdbook build

  test:
    desc: Run tests
    cmd: go test ./...

  test-race:
    desc: Run tests with race detector
    env:
      CGO_ENABLED: 1
    cmd: go test -race -count=1 -timeout=30s ./...