version: '3'

env:
  CGO_ENABLED: 0

tasks:
  default:
    desc: List available tasks
    cmd: task --list

  cli-docs:
    desc: Generate CLI reference
    cmds: 
      - go run -tags docs ./cmd/hclapi
      - bunx prettier@latest --write docs/content/cli

  cli-man:
    desc: Generate man pages
    cmd: go run -tags man ./cmd/hclapi

  www-serve:
    desc: Serve website
    dir: www
    cmd: bun run dev

  www-build:
    desc: Build website
    dir: www
    cmd: bun run build

  test:
    desc: Run tests
    cmd: go test ./...

  test-race:
    desc: Run tests with race detector
    env:
      CGO_ENABLED: 1
    cmd: go test -race -count=1 -timeout=30s ./...

  test-integration:
    desc: Run containerized integration tests agains real services
    cmd: go test -v -tags=integration -run="^TestIntegration" -timeout=5m ./...

  lint:
    desc: Lint code
    cmd: golangci-lint run

  fmt:
    desc: Format code
    cmd: golangci-lint fmt

  fmt-www:
    desc: Format www
    cmd: bunx prettier@latest --write www/content

  update:
    desc: Update dependencies
    cmds: 
      - go get -u ./...
      - go mod tidy

    
