services:
  postgres:
    image: postgres:18-alpine
    container_name: hclapi-03-postgres
    environment:
      POSTGRES_USER: hclapi
      POSTGRES_PASSWORD: hclapi_password
      POSTGRES_DB: hclapi_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hclapi -d hclapi_db"]
      interval: 2s
      timeout: 3s
      retries: 10

  hclapi:
    image: ghcr.io/ju4n97/hclapi:latest
    container_name: hclapi-03-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://hclapi:hclapi_password@postgres:5432/hclapi_db?sslmode=disable"
    volumes:
      - ./main.hcl:/etc/hclapi/main.hcl:ro
    ports:
      - "8080:8080"
    restart: unless-stopped