blank_issues_enabled: true

contact_links:
  - name: Ideas
    url: https://github.com/ju4n97/hclapi/categories/ideas
    about: Share ideas and feature suggestions.

  - name: Questions
    url: https://github.com/ju4n97/discussions/categories/q-a
    about: Ask questions and get help.
