services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: hclapi-clickhouse-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "9000:9000"
      - "8123:8123"